import type { Question } from "./students";

export const entrepreneurQuestions: Question[] = [
  // MODULE 1
  {
    id: 1,
    module: "MODULE 1: THE AI ENTREPRENEUR MINDSET",
    question: "What was the main problem Adekunle faced in his catering business despite being successful?",
    options: {
      A: "He was losing money",
      B: "He was always exhausted and doing work of six people",
      C: "He had no employees",
      D: "He was not making any profit",
    },
    correct: "B",
  },
  {
    id: 2,
    module: "MODULE 1: THE AI ENTREPRENEUR MINDSET",
    question: "According to the module, what is the \"Old Entrepreneur's Trap\"?",
    options: {
      A: "Not having enough employees",
      B: "Working hard but working small by doing everything themselves",
      C: "Not using any technology",
      D: "Having too many clients",
    },
    correct: "B",
  },
  {
    id: 3,
    module: "MODULE 1: THE AI ENTREPRENEUR MINDSET",
    question: "What does AI help entrepreneurs with according to Module 1?",
    options: {
      A: "Making all business decisions",
      B: "Replacing employees completely",
      C: "Taking over repetitive, administrative, information-processing work",
      D: "Eliminating the need for human judgment",
    },
    correct: "C",
  },
  {
    id: 4,
    module: "MODULE 1: THE AI ENTREPRENEUR MINDSET",
    question: "What is the \"Anti-Pattern\" described in the module?",
    options: {
      A: "Using AI for everything without oversight, creating generic content",
      B: "Not using AI at all",
      C: "Working too many hours",
      D: "Having too many employees",
    },
    correct: "A",
  },
  {
    id: 5,
    module: "MODULE 1: THE AI ENTREPRENEUR MINDSET",
    question: "What question separates entrepreneurs who survive from those who thrive?",
    options: {
      A: "\"How much money am I making?\"",
      B: "\"What would I do with the time returned to me by AI?\"",
      C: "\"How many employees do I have?\"",
      D: "\"What tools should I buy?\"",
    },
    correct: "B",
  },
  {
    id: 6,
    module: "MODULE 1: THE AI ENTREPRENEUR MINDSET",
    question: "Which of these is NOT a role AI can play in a business according to the module?",
    options: {
      A: "Research assistant",
      B: "CEO decision maker",
      C: "Marketing assistant",
      D: "Customer support assistant",
    },
    correct: "B",
  },
  {
    id: 7,
    module: "MODULE 1: THE AI ENTREPRENEUR MINDSET",
    question: "What should AI do to an entrepreneur's judgment?",
    options: {
      A: "Replace it completely",
      B: "Multiply or amplify it",
      C: "Ignore it",
      D: "Make it unnecessary",
    },
    correct: "B",
  },

  // MODULE 2
  {
    id: 8,
    module: "MODULE 2: BUILDING YOUR AI OPERATING SYSTEM",
    question: "What did Chidi learn from his successful friend?",
    options: {
      A: "To work harder",
      B: "To have a system instead of just tools",
      C: "To hire more employees",
      D: "To work on weekends",
    },
    correct: "B",
  },
  {
    id: 9,
    module: "MODULE 2: BUILDING YOUR AI OPERATING SYSTEM",
    question: "According to the module, what is the difference between tools and systems?",
    options: {
      A: "Tools are expensive, systems are cheap",
      B: "Tools are used occasionally, systems are built once and run forever",
      C: "Tools are for big companies, systems are for small ones",
      D: "There is no difference",
    },
    correct: "B",
  },
  {
    id: 10,
    module: "MODULE 2: BUILDING YOUR AI OPERATING SYSTEM",
    question: "What is the correct sequence for building an AI system?",
    options: {
      A: "System → Assistant → Workflow → Task",
      B: "Task → Workflow → Assistant → System",
      C: "Workflow → Task → System → Assistant",
      D: "Assistant → System → Task → Workflow",
    },
    correct: "B",
  },
  {
    id: 11,
    module: "MODULE 2: BUILDING YOUR AI OPERATING SYSTEM",
    question: "Which tasks should be handled by AI according to the module?",
    options: {
      A: "Tasks requiring unique judgment",
      B: "Strategic decisions",
      C: "Repeatable, low-judgment tasks",
      D: "All tasks in the business",
    },
    correct: "C",
  },
  {
    id: 12,
    module: "MODULE 2: BUILDING YOUR AI OPERATING SYSTEM",
    question: "What does Claude Projects allow you to create?",
    options: {
      A: "Only one workspace",
      B: "Dedicated workspaces for different parts of your business",
      C: "Social media posts",
      D: "Email templates only",
    },
    correct: "B",
  },
  {
    id: 13,
    module: "MODULE 2: BUILDING YOUR AI OPERATING SYSTEM",
    question: "What is the entrepreneur still responsible for even with an AI operating system?",
    options: {
      A: "Nothing, AI handles everything",
      B: "Only administrative tasks",
      C: "Judgment on major decisions and relationship building",
      D: "Only content creation",
    },
    correct: "C",
  },
  {
    id: 14,
    module: "MODULE 2: BUILDING YOUR AI OPERATING SYSTEM",
    question: "Which Google tool connects AI to Gmail, calendar, drive, and docs?",
    options: {
      A: "Google Search",
      B: "Gemini and Google Workspace",
      C: "Google Maps",
      D: "Google Translate",
    },
    correct: "B",
  },

  // MODULE 3
  {
    id: 15,
    module: "MODULE 3: BUILDING AND AMPLIFYING YOUR BRAND WITH AI",
    question: "What was Temitope's problem before using AI?",
    options: {
      A: "She had no knowledge",
      B: "She was knowledgeable but invisible",
      C: "She had too many followers",
      D: "She was making too much money",
    },
    correct: "B",
  },
  {
    id: 16,
    module: "MODULE 3: BUILDING AND AMPLIFYING YOUR BRAND WITH AI",
    question: "What is the correct content workflow according to the module?",
    options: {
      A: "Publishing → Ideas → Research → Creation",
      B: "Ideas → Research → Positioning → Creation → Repurposing → Publishing → Analysis → Improvement",
      C: "Creation → Publishing → Analysis → Ideas",
      D: "Repurposing → Ideas → Research → Publishing",
    },
    correct: "B",
  },
  {
    id: 17,
    module: "MODULE 3: BUILDING AND AMPLIFYING YOUR BRAND WITH AI",
    question: "What does AI NOT replace in content creation?",
    options: {
      A: "Drafting",
      B: "Research",
      C: "Your perspective and personality",
      D: "Structuring",
    },
    correct: "C",
  },
  {
    id: 18,
    module: "MODULE 3: BUILDING AND AMPLIFYING YOUR BRAND WITH AI",
    question: "Which tool is best for AI avatar videos according to the module?",
    options: {
      A: "Capcut",
      B: "HeyGen",
      C: "ElevenLabs",
      D: "OpuClip",
    },
    correct: "B",
  },
  {
    id: 19,
    module: "MODULE 3: BUILDING AND AMPLIFYING YOUR BRAND WITH AI",
    question: "What is the purpose of repurposing content?",
    options: {
      A: "To create less value",
      B: "To distribute more value to more people efficiently",
      C: "To avoid creating new content",
      D: "To make content worse",
    },
    correct: "B",
  },
  {
    id: 20,
    module: "MODULE 3: BUILDING AND AMPLIFYING YOUR BRAND WITH AI",
    question: "According to the module, what does positioning mean for your brand?",
    options: {
      A: "Creating generic content",
      B: "Deciding your unique angle and what makes you different",
      C: "Copying what others do",
      D: "Posting at the right time",
    },
    correct: "B",
  },
  {
    id: 21,
    module: "MODULE 3: BUILDING AND AMPLIFYING YOUR BRAND WITH AI",
    question: "Which tool is best for voiceovers according to the module?",
    options: {
      A: "Google Flow",
      B: "Midjourney",
      C: "ElevenLabs",
      D: "Capcut",
    },
    correct: "C",
  },

  // MODULE 4
  {
    id: 22,
    module: "MODULE 4: GROWING & MONETIZING YOUR AUDIENCE WITH AI",
    question: "What was Ama's main problem despite having 30,000 followers?",
    options: {
      A: "She had no followers",
      B: "She had an audience but not a business",
      C: "Her content was poor quality",
      D: "She had too many products",
    },
    correct: "B",
  },
  {
    id: 23,
    module: "MODULE 4: GROWING & MONETIZING YOUR AUDIENCE WITH AI",
    question: "What is the correct audience-to-business pipeline?",
    options: {
      A: "Sale → Trust → Lead → Attention",
      B: "Attention → Audience → Trust → Lead → Offer → Sale → Relationship → Repeat Business",
      C: "Relationship → Sale → Attention → Audience",
      D: "Offer → Lead → Trust → Sale",
    },
    correct: "B",
  },
  {
    id: 24,
    module: "MODULE 4: GROWING & MONETIZING YOUR AUDIENCE WITH AI",
    question: "What is a lead according to the module?",
    options: {
      A: "Anyone who follows you on social media",
      B: "Someone who has expressed interest and given permission to talk to them",
      C: "Someone who has already bought from you",
      D: "Anyone who sees your content",
    },
    correct: "B",
  },
  {
    id: 25,
    module: "MODULE 4: GROWING & MONETIZING YOUR AUDIENCE WITH AI",
    question: "What is the purpose of a lead magnet?",
    options: {
      A: "To make money directly",
      B: "To provide immediate value and build trust in exchange for contact information",
      C: "To replace your main product",
      D: "To confuse customers",
    },
    correct: "B",
  },
  {
    id: 26,
    module: "MODULE 4: GROWING & MONETIZING YOUR AUDIENCE WITH AI",
    question: "According to the module, acquiring a new customer costs how much more than retaining an existing one?",
    options: {
      A: "Same cost",
      B: "Two to three times more",
      C: "Five to seven times more",
      D: "Ten times more",
    },
    correct: "C",
  },
  {
    id: 27,
    module: "MODULE 4: GROWING & MONETIZING YOUR AUDIENCE WITH AI",
    question: "What role does the AI Sales Assistant play?",
    options: {
      A: "Makes all sales decisions",
      B: "Personalises outreach, follows up, and qualifies leads",
      C: "Closes all sales automatically",
      D: "Replaces the sales team completely",
    },
    correct: "B",
  },
  {
    id: 28,
    module: "MODULE 4: GROWING & MONETIZING YOUR AUDIENCE WITH AI",
    question: "What is the warning given at the end of Module 4?",
    options: {
      A: "AI can build the business for you",
      B: "AI can replace all human relationships",
      C: "AI can help but cannot build the business for you",
      D: "You should only use AI for everything",
    },
    correct: "C",
  },
  {
    id: 29,
    module: "MODULE 4: GROWING & MONETIZING YOUR AUDIENCE WITH AI",
    question: "What does the AI Audience Researcher do?",
    options: {
      A: "Creates content automatically",
      B: "Analyses conversations, identifies patterns, and surfaces customer needs",
      C: "Closes sales",
      D: "Manages finances",
    },
    correct: "B",
  },
  {
    id: 30,
    module: "MODULE 4: GROWING & MONETIZING YOUR AUDIENCE WITH AI",
    question: "Which of these CANNOT be automated according to Module 4?",
    options: {
      A: "Drafting emails",
      B: "Researching audience",
      C: "Building trust and connecting with people",
      D: "Creating lead magnets",
    },
    correct: "C",
  },
];